# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.1"
  nodejs_min: "22"
  python_check_max: "3.14"
  cov_fail_under: "34"

recipe:
  name: jupyter-builder-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-builder/jupyter_builder-${{ version }}.tar.gz
  sha256: 1a13977912b08deda77fce2c803940131c27cf77a27ed64b9ffca25aa0ed7e6c

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: jupyter-builder
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - jupyter-builder = jupyter_builder.main:main
          - jlpm = jupyter_builder.jlpm:main
    requirements:
      host:
        - hatch-nodejs-version >=0.3.2
        - hatchling >=1.21.1
        - pip
        - python ${{ python_min }}.*
      run:
        - jupyter_core
        - python >=${{ python_min }}
        - tomli
        - traitlets
      run_constraints:
        - nodejs >=${{ nodejs_min }}
    tests:
      - python:
          imports: jupyter_builder
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - script:
          - jupyter-builder --help

  - package:
      name: jupyter-builder-with-nodejs
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyter-builder", exact=True) }}
        - nodejs ${{ nodejs_min }}.*
    tests:
      - script:
          - jlpm --help
      - requirements:
          run:
            - copier >=9.3,<10
            - coverage
            - jinja2-time
            - mypy
            - nodejs ${{ nodejs_min }}.*
            - pytest >=7.0
            - pytest-html
            - python ${{ python_min }}.*
        files:
          source:
            - tests/
        script:
          env:
            PYTEST_ADDOPTS: >
              --html=pytest.html
              --override-ini=generate_report_on_test=true
              -k "not watch"
          content:
            - coverage run --source=jupyter_builder --branch -m pytest -vv --tb=long --color=yes
            - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}
            - mypy -p jupyter_builder --exclude "debug_log_file_mixin\.py"
      # see: https://github.com/conda-forge/jupyterlab-feedstock/issues/466
      # - downstream: jupyterlab
      # - downstream: notebook
    about:
      summary: JupyterLab build tools (with nodejs)

about:
  summary: JupyterLab build tools
  license: BSD-3-Clause AND MIT AND ISC
  license_file:
    - LICENSE
    - THIRD_PARTY_LICENSES/
  homepage: https://pypi.org/project/jupyter-builder
  repository: https://github.com/jupyterlab/jupyter-builder

extra:
  feedstock-name: jupyter-builder
  recipe-maintainers:
    - darshan808
    - krassowski
    - bollwyvl
